apiVersion: v1
kind: ConfigMap
metadata:
  name: qm-beta-configmap
data:
  tls.mqsc: |
    DEFINE QLOCAL('BETA.QUEUE1') DEFPSIST(YES) REPLACE 
    DEFINE QLOCAL('BETA.QUEUE2') DEFPSIST(YES) REPLACE 
    DEFINE CHANNEL(HAQMCHL) CHLTYPE(SVRCONN) TRPTYPE(TCP) SSLCAUTH(OPTIONAL) SSLCIPH('ANY_TLS12_OR_HIGHER')
    SET CHLAUTH(HAQMCHL) TYPE(BLOCKUSER) USERLIST('nobody') ACTION(ADD)
    ALTER QMGR CERTVPOL(ANY)
    REFRESH SECURITY TYPE(SSL)
